import { ChatEmbed } from "../embed/chat";
import { ChatMessageType } from "./type";

/** Type definition of a general chat message. */
export type ChatMessage = {
    /** Id of the message. */
    id: string;
    /**
     * Type of the chat message.
     * `default` messages are user or bot generated,
     * `system` messages are generated by Guilded,
     */
    type: ChatMessageType;
    /**
     * Id of the server.
     * Can be undefined if the message was send through a DM.
     */
    serverId?: string;
    /** Id of the channel. */
    channelId: string;
    /** Content of the message in markdown format. */
    content: string;
    /**
     * Embeds of this message.
     * @minimum 1
     * @maxiumum 2
     */
    embeds?: ChatEmbed[];
    /** Ids of the messages which have been replied to. */
    replyMessageIds?: string[];
    /**
     * If set to `true`,
     * this message will only be displayed to those,
     * who have been mentioned or replied to.
     */
    isPrivate?: boolean;
    /** Timestamp in ISO 8601 format of when the message was created at. */
    createdAt: string;
    /**
     * Id of the user who created this message.
     *
     * NOTE: If this message includes a `createdByWebhookId`,
     * then this field can be ignored
     * since the value of this field will then always be `Ann6LewA`
     */
    createdBy: string;
    /**
     * Id of the webhook which created this message,
     * if this message has been created by a webhook.
     */
    createdByWebhookId?: string;
    /**
     * Timestamp in ISO 8601 format of when the message was updated,
     * if relevant
     */
    updatedAt?: string;
};
