/** Names of events which Guilded sends us sometimes with a gateway payload. */
export type EventName =
    | "ChatMessageCreated"
    | "ChatMessageUpdated"
    | "ChatMessageDeleted"
    | "TeamMemberJoined"
    | "TeamMemberRemoved"
    | "TeamMemberBanned"
    | "TeamMemberUnbanned"
    | "TeamMemberUpdated"
    | "teamRolesUpdated"
    | "TeamChannelCreated"
    | "TeamChannelUpdated"
    | "TeamChannelDeleted"
    | "TeamWebhookCreated"
    | "TeamWebhookUpdated"
    | "DocCreated"
    | "DocUpdated"
    | "DocDeleted"
    | "ListItemCreated"
    | "ListItemUpdated"
    | "ListItemDeleted"
    | "ListItemCompleted"
    | "ListItemUncompleted";
