// @ts-check
/* eslint-disable no-undef */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
    // But you can create a sidebar manually
};

module.exports = sidebars;
