name: Test Website build

on:
    pull_request:
        paths:
            - "website/**"

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    test-deploy:
        name: Test building
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14.x
                  cache: npm
                  cache-dependency-path: website/package-lock.json
            - name: Test build
              working-directory: website
              run: |
                  npm ci
                  npm run build
